project_id = "owykkhwqpnumvgdeugmj"

[functions.sync-id-contacto]
verify_jwt = false

[functions.enviar-expansion]
verify_jwt = false

[functions.ensure-lead]
verify_jwt = false

[functions.log-auto-message]
verify_jwt = false

[functions.sheets-country-kpis]
verify_jwt = true

[functions.sheets-leads]
verify_jwt = true

[functions.resync-leads-sheet]
verify_jwt = true

[functions.voice-leads]
verify_jwt = true

[functions.tag-lead]
verify_jwt = false

[functions.etiquetar-ia]
verify_jwt = false

[functions.send-auto-tag-chile]
verify_jwt = false

[functions.cron-etiquetado-ia]
verify_jwt = false

[functions.send-personalized-campaign]
verify_jwt = true

[functions.buscar-leads]
verify_jwt = true


